// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/data/data.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data type enumeration
type DataType int32

const (
	DataType_DATA_TYPE_UNSPECIFIED DataType = 0
	DataType_DATA_TYPE_CREDENTIALS DataType = 1 // Login/password pairs
	DataType_DATA_TYPE_TEXT        DataType = 2 // Text notes
	DataType_DATA_TYPE_BINARY      DataType = 3 // Binary files
	DataType_DATA_TYPE_CARD        DataType = 4 // Bank card data
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "DATA_TYPE_UNSPECIFIED",
		1: "DATA_TYPE_CREDENTIALS",
		2: "DATA_TYPE_TEXT",
		3: "DATA_TYPE_BINARY",
		4: "DATA_TYPE_CARD",
	}
	DataType_value = map[string]int32{
		"DATA_TYPE_UNSPECIFIED": 0,
		"DATA_TYPE_CREDENTIALS": 1,
		"DATA_TYPE_TEXT":        2,
		"DATA_TYPE_BINARY":      3,
		"DATA_TYPE_CARD":        4,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_data_data_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_proto_data_data_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{0}
}

// Sync action enumeration
type SyncAction int32

const (
	SyncAction_SYNC_ACTION_UNSPECIFIED SyncAction = 0
	SyncAction_SYNC_ACTION_CREATE      SyncAction = 1
	SyncAction_SYNC_ACTION_UPDATE      SyncAction = 2
	SyncAction_SYNC_ACTION_DELETE      SyncAction = 3
)

// Enum value maps for SyncAction.
var (
	SyncAction_name = map[int32]string{
		0: "SYNC_ACTION_UNSPECIFIED",
		1: "SYNC_ACTION_CREATE",
		2: "SYNC_ACTION_UPDATE",
		3: "SYNC_ACTION_DELETE",
	}
	SyncAction_value = map[string]int32{
		"SYNC_ACTION_UNSPECIFIED": 0,
		"SYNC_ACTION_CREATE":      1,
		"SYNC_ACTION_UPDATE":      2,
		"SYNC_ACTION_DELETE":      3,
	}
)

func (x SyncAction) Enum() *SyncAction {
	p := new(SyncAction)
	*p = x
	return p
}

func (x SyncAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_data_data_proto_enumTypes[1].Descriptor()
}

func (SyncAction) Type() protoreflect.EnumType {
	return &file_proto_data_data_proto_enumTypes[1]
}

func (x SyncAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncAction.Descriptor instead.
func (SyncAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{1}
}

// Conflict resolution strategy
type ConflictResolutionStrategy int32

const (
	ConflictResolutionStrategy_CONFLICT_RESOLVE_UNSPECIFIED  ConflictResolutionStrategy = 0
	ConflictResolutionStrategy_CONFLICT_RESOLVE_BY_VERSION   ConflictResolutionStrategy = 1
	ConflictResolutionStrategy_CONFLICT_RESOLVE_BY_TIMESTAMP ConflictResolutionStrategy = 2
	ConflictResolutionStrategy_CONFLICT_RESOLVE_SERVER_WINS  ConflictResolutionStrategy = 3
	ConflictResolutionStrategy_CONFLICT_RESOLVE_CLIENT_WINS  ConflictResolutionStrategy = 4
)

// Enum value maps for ConflictResolutionStrategy.
var (
	ConflictResolutionStrategy_name = map[int32]string{
		0: "CONFLICT_RESOLVE_UNSPECIFIED",
		1: "CONFLICT_RESOLVE_BY_VERSION",
		2: "CONFLICT_RESOLVE_BY_TIMESTAMP",
		3: "CONFLICT_RESOLVE_SERVER_WINS",
		4: "CONFLICT_RESOLVE_CLIENT_WINS",
	}
	ConflictResolutionStrategy_value = map[string]int32{
		"CONFLICT_RESOLVE_UNSPECIFIED":  0,
		"CONFLICT_RESOLVE_BY_VERSION":   1,
		"CONFLICT_RESOLVE_BY_TIMESTAMP": 2,
		"CONFLICT_RESOLVE_SERVER_WINS":  3,
		"CONFLICT_RESOLVE_CLIENT_WINS":  4,
	}
)

func (x ConflictResolutionStrategy) Enum() *ConflictResolutionStrategy {
	p := new(ConflictResolutionStrategy)
	*p = x
	return p
}

func (x ConflictResolutionStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConflictResolutionStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_data_data_proto_enumTypes[2].Descriptor()
}

func (ConflictResolutionStrategy) Type() protoreflect.EnumType {
	return &file_proto_data_data_proto_enumTypes[2]
}

func (x ConflictResolutionStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConflictResolutionStrategy.Descriptor instead.
func (ConflictResolutionStrategy) EnumDescriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{2}
}

// Store data request
type StoreDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          DataType               `protobuf:"varint,2,opt,name=type,proto3,enum=data.DataType" json:"type,omitempty"`
	Metadata      string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"` // JSON metadata (name, description, etc.)
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`         // Encrypted data payload
	Checksum      string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"` // Data integrity checksum
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreDataRequest) Reset() {
	*x = StoreDataRequest{}
	mi := &file_proto_data_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreDataRequest) ProtoMessage() {}

func (x *StoreDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreDataRequest.ProtoReflect.Descriptor instead.
func (*StoreDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{0}
}

func (x *StoreDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StoreDataRequest) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_DATA_TYPE_UNSPECIFIED
}

func (x *StoreDataRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *StoreDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StoreDataRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

// Store data response
type StoreDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DataId        string                 `protobuf:"bytes,3,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreDataResponse) Reset() {
	*x = StoreDataResponse{}
	mi := &file_proto_data_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreDataResponse) ProtoMessage() {}

func (x *StoreDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreDataResponse.ProtoReflect.Descriptor instead.
func (*StoreDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{1}
}

func (x *StoreDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StoreDataResponse) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *StoreDataResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Get data request
type GetDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DataId        string                 `protobuf:"bytes,2,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataRequest) Reset() {
	*x = GetDataRequest{}
	mi := &file_proto_data_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataRequest) ProtoMessage() {}

func (x *GetDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataRequest.ProtoReflect.Descriptor instead.
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{2}
}

func (x *GetDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDataRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

// Get data response
type GetDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DataItem      *DataItem              `protobuf:"bytes,3,opt,name=data_item,json=dataItem,proto3" json:"data_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataResponse) Reset() {
	*x = GetDataResponse{}
	mi := &file_proto_data_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataResponse) ProtoMessage() {}

func (x *GetDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataResponse.ProtoReflect.Descriptor instead.
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{3}
}

func (x *GetDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetDataResponse) GetDataItem() *DataItem {
	if x != nil {
		return x.DataItem
	}
	return nil
}

// Get user data request
type GetUserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          DataType               `protobuf:"varint,2,opt,name=type,proto3,enum=data.DataType" json:"type,omitempty"` // Optional filter by type
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                  // Optional limit
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`                // Optional offset for pagination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDataRequest) Reset() {
	*x = GetUserDataRequest{}
	mi := &file_proto_data_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataRequest) ProtoMessage() {}

func (x *GetUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataRequest.ProtoReflect.Descriptor instead.
func (*GetUserDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserDataRequest) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_DATA_TYPE_UNSPECIFIED
}

func (x *GetUserDataRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserDataRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Get user data response
type GetUserDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DataItems     []*DataItem            `protobuf:"bytes,3,rep,name=data_items,json=dataItems,proto3" json:"data_items,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDataResponse) Reset() {
	*x = GetUserDataResponse{}
	mi := &file_proto_data_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataResponse) ProtoMessage() {}

func (x *GetUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataResponse.ProtoReflect.Descriptor instead.
func (*GetUserDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetUserDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserDataResponse) GetDataItems() []*DataItem {
	if x != nil {
		return x.DataItems
	}
	return nil
}

func (x *GetUserDataResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Update data request
type UpdateDataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DataId         string                 `protobuf:"bytes,2,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Metadata       string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`                                    // Updated metadata
	Data           []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                                            // Updated encrypted data
	Checksum       string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`                                    // Updated checksum
	CurrentVersion int64                  `protobuf:"varint,6,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"` // For optimistic locking
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateDataRequest) Reset() {
	*x = UpdateDataRequest{}
	mi := &file_proto_data_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataRequest) ProtoMessage() {}

func (x *UpdateDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateDataRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *UpdateDataRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *UpdateDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateDataRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *UpdateDataRequest) GetCurrentVersion() int64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

// Update data response
type UpdateDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NewVersion    int64                  `protobuf:"varint,3,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDataResponse) Reset() {
	*x = UpdateDataResponse{}
	mi := &file_proto_data_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataResponse) ProtoMessage() {}

func (x *UpdateDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataResponse.ProtoReflect.Descriptor instead.
func (*UpdateDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateDataResponse) GetNewVersion() int64 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

// Delete data request
type DeleteDataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DataId         string                 `protobuf:"bytes,2,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	CurrentVersion int64                  `protobuf:"varint,3,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"` // For optimistic locking
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteDataRequest) Reset() {
	*x = DeleteDataRequest{}
	mi := &file_proto_data_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataRequest) ProtoMessage() {}

func (x *DeleteDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataRequest.ProtoReflect.Descriptor instead.
func (*DeleteDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteDataRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *DeleteDataRequest) GetCurrentVersion() int64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

// Delete data response
type DeleteDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDataResponse) Reset() {
	*x = DeleteDataResponse{}
	mi := &file_proto_data_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataResponse) ProtoMessage() {}

func (x *DeleteDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataResponse.ProtoReflect.Descriptor instead.
func (*DeleteDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Sync data request
type SyncDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LastSync      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_sync,json=lastSync,proto3" json:"last_sync,omitempty"`
	ExcludeIds    []string               `protobuf:"bytes,3,rep,name=exclude_ids,json=excludeIds,proto3" json:"exclude_ids,omitempty"` // IDs to exclude from sync
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDataRequest) Reset() {
	*x = SyncDataRequest{}
	mi := &file_proto_data_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDataRequest) ProtoMessage() {}

func (x *SyncDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDataRequest.ProtoReflect.Descriptor instead.
func (*SyncDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{10}
}

func (x *SyncDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SyncDataRequest) GetLastSync() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSync
	}
	return nil
}

func (x *SyncDataRequest) GetExcludeIds() []string {
	if x != nil {
		return x.ExcludeIds
	}
	return nil
}

// Sync data response
type SyncDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedItems  []*DataItem            `protobuf:"bytes,3,rep,name=updated_items,json=updatedItems,proto3" json:"updated_items,omitempty"`
	DeletedIds    []string               `protobuf:"bytes,4,rep,name=deleted_ids,json=deletedIds,proto3" json:"deleted_ids,omitempty"`
	SyncTimestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=sync_timestamp,json=syncTimestamp,proto3" json:"sync_timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDataResponse) Reset() {
	*x = SyncDataResponse{}
	mi := &file_proto_data_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDataResponse) ProtoMessage() {}

func (x *SyncDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDataResponse.ProtoReflect.Descriptor instead.
func (*SyncDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{11}
}

func (x *SyncDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncDataResponse) GetUpdatedItems() []*DataItem {
	if x != nil {
		return x.UpdatedItems
	}
	return nil
}

func (x *SyncDataResponse) GetDeletedIds() []string {
	if x != nil {
		return x.DeletedIds
	}
	return nil
}

func (x *SyncDataResponse) GetSyncTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.SyncTimestamp
	}
	return nil
}

// Data item message
type DataItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          DataType               `protobuf:"varint,3,opt,name=type,proto3,enum=data.DataType" json:"type,omitempty"`
	Metadata      string                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`                     // JSON metadata
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`                             // Encrypted data
	Checksum      string                 `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`                     // Data integrity checksum
	Version       int64                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`                      // Version for conflict resolution
	IsDeleted     bool                   `protobuf:"varint,8,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"` // Soft delete flag
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataItem) Reset() {
	*x = DataItem{}
	mi := &file_proto_data_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataItem) ProtoMessage() {}

func (x *DataItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataItem.ProtoReflect.Descriptor instead.
func (*DataItem) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{12}
}

func (x *DataItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DataItem) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_DATA_TYPE_UNSPECIFIED
}

func (x *DataItem) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *DataItem) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataItem) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *DataItem) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DataItem) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *DataItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DataItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Credentials data structure (for metadata)
type CredentialsMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // Service/site name
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // Optional description
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`                 // Optional URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsMetadata) Reset() {
	*x = CredentialsMetadata{}
	mi := &file_proto_data_data_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsMetadata) ProtoMessage() {}

func (x *CredentialsMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsMetadata.ProtoReflect.Descriptor instead.
func (*CredentialsMetadata) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{13}
}

func (x *CredentialsMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CredentialsMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CredentialsMetadata) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Text data structure (for metadata)
type TextMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // Note title
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // Optional description
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`               // Optional tags
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextMetadata) Reset() {
	*x = TextMetadata{}
	mi := &file_proto_data_data_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextMetadata) ProtoMessage() {}

func (x *TextMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextMetadata.ProtoReflect.Descriptor instead.
func (*TextMetadata) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{14}
}

func (x *TextMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TextMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TextMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Binary file structure (for metadata)
type BinaryMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`                          // Original filename
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // MIME type
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`         // File size in bytes
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                    // Optional description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryMetadata) Reset() {
	*x = BinaryMetadata{}
	mi := &file_proto_data_data_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryMetadata) ProtoMessage() {}

func (x *BinaryMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryMetadata.ProtoReflect.Descriptor instead.
func (*BinaryMetadata) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{15}
}

func (x *BinaryMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *BinaryMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *BinaryMetadata) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *BinaryMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Bank card structure (for metadata)
type CardMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                         // Card name/description
	BankName      string                 `protobuf:"bytes,2,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"` // Bank name
	CardType      string                 `protobuf:"bytes,3,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"` // Visa, MasterCard, etc.
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`           // Optional description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardMetadata) Reset() {
	*x = CardMetadata{}
	mi := &file_proto_data_data_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardMetadata) ProtoMessage() {}

func (x *CardMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardMetadata.ProtoReflect.Descriptor instead.
func (*CardMetadata) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{16}
}

func (x *CardMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CardMetadata) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *CardMetadata) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *CardMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Sync item for advanced synchronization
type SyncItem struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	Action             SyncAction                 `protobuf:"varint,1,opt,name=action,proto3,enum=data.SyncAction" json:"action,omitempty"`
	DataItem           *DataItem                  `protobuf:"bytes,2,opt,name=data_item,json=dataItem,proto3" json:"data_item,omitempty"`
	ConflictResolution ConflictResolutionStrategy `protobuf:"varint,3,opt,name=conflict_resolution,json=conflictResolution,proto3,enum=data.ConflictResolutionStrategy" json:"conflict_resolution,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SyncItem) Reset() {
	*x = SyncItem{}
	mi := &file_proto_data_data_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncItem) ProtoMessage() {}

func (x *SyncItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncItem.ProtoReflect.Descriptor instead.
func (*SyncItem) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{17}
}

func (x *SyncItem) GetAction() SyncAction {
	if x != nil {
		return x.Action
	}
	return SyncAction_SYNC_ACTION_UNSPECIFIED
}

func (x *SyncItem) GetDataItem() *DataItem {
	if x != nil {
		return x.DataItem
	}
	return nil
}

func (x *SyncItem) GetConflictResolution() ConflictResolutionStrategy {
	if x != nil {
		return x.ConflictResolution
	}
	return ConflictResolutionStrategy_CONFLICT_RESOLVE_UNSPECIFIED
}

// Sync result for advanced synchronization
type SyncResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ItemId           string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Action           SyncAction             `protobuf:"varint,2,opt,name=action,proto3,enum=data.SyncAction" json:"action,omitempty"`
	Success          bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error            string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ConflictResolved bool                   `protobuf:"varint,5,opt,name=conflict_resolved,json=conflictResolved,proto3" json:"conflict_resolved,omitempty"`
	FinalVersion     int64                  `protobuf:"varint,6,opt,name=final_version,json=finalVersion,proto3" json:"final_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncResult) Reset() {
	*x = SyncResult{}
	mi := &file_proto_data_data_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResult) ProtoMessage() {}

func (x *SyncResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResult.ProtoReflect.Descriptor instead.
func (*SyncResult) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{18}
}

func (x *SyncResult) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *SyncResult) GetAction() SyncAction {
	if x != nil {
		return x.Action
	}
	return SyncAction_SYNC_ACTION_UNSPECIFIED
}

func (x *SyncResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SyncResult) GetConflictResolved() bool {
	if x != nil {
		return x.ConflictResolved
	}
	return false
}

func (x *SyncResult) GetFinalVersion() int64 {
	if x != nil {
		return x.FinalVersion
	}
	return 0
}

// Advanced synchronization request
type SynchronizeDataRequest struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	UserId           string                     `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LastSyncTime     *timestamppb.Timestamp     `protobuf:"bytes,2,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	Items            []*SyncItem                `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	ConflictStrategy ConflictResolutionStrategy `protobuf:"varint,4,opt,name=conflict_strategy,json=conflictStrategy,proto3,enum=data.ConflictResolutionStrategy" json:"conflict_strategy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SynchronizeDataRequest) Reset() {
	*x = SynchronizeDataRequest{}
	mi := &file_proto_data_data_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynchronizeDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynchronizeDataRequest) ProtoMessage() {}

func (x *SynchronizeDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynchronizeDataRequest.ProtoReflect.Descriptor instead.
func (*SynchronizeDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{19}
}

func (x *SynchronizeDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SynchronizeDataRequest) GetLastSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncTime
	}
	return nil
}

func (x *SynchronizeDataRequest) GetItems() []*SyncItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SynchronizeDataRequest) GetConflictStrategy() ConflictResolutionStrategy {
	if x != nil {
		return x.ConflictStrategy
	}
	return ConflictResolutionStrategy_CONFLICT_RESOLVE_UNSPECIFIED
}

// Advanced synchronization response
type SynchronizeDataResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Results        []*SyncResult          `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	ServerChanges  []*SyncItem            `protobuf:"bytes,4,rep,name=server_changes,json=serverChanges,proto3" json:"server_changes,omitempty"`
	SyncTimestamp  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=sync_timestamp,json=syncTimestamp,proto3" json:"sync_timestamp,omitempty"`
	TotalConflicts int32                  `protobuf:"varint,6,opt,name=total_conflicts,json=totalConflicts,proto3" json:"total_conflicts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SynchronizeDataResponse) Reset() {
	*x = SynchronizeDataResponse{}
	mi := &file_proto_data_data_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynchronizeDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynchronizeDataResponse) ProtoMessage() {}

func (x *SynchronizeDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynchronizeDataResponse.ProtoReflect.Descriptor instead.
func (*SynchronizeDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{20}
}

func (x *SynchronizeDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SynchronizeDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SynchronizeDataResponse) GetResults() []*SyncResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SynchronizeDataResponse) GetServerChanges() []*SyncItem {
	if x != nil {
		return x.ServerChanges
	}
	return nil
}

func (x *SynchronizeDataResponse) GetSyncTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.SyncTimestamp
	}
	return nil
}

func (x *SynchronizeDataResponse) GetTotalConflicts() int32 {
	if x != nil {
		return x.TotalConflicts
	}
	return 0
}

var File_proto_data_data_proto protoreflect.FileDescriptor

const file_proto_data_data_proto_rawDesc = "" +
	"\n" +
	"\x15proto/data/data.proto\x12\x04data\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x01\n" +
	"\x10StoreDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\"\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0e.data.DataTypeR\x04type\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\"z\n" +
	"\x11StoreDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\adata_id\x18\x03 \x01(\tR\x06dataId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\"B\n" +
	"\x0eGetDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\adata_id\x18\x02 \x01(\tR\x06dataId\"r\n" +
	"\x0fGetDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\tdata_item\x18\x03 \x01(\v2\x0e.data.DataItemR\bdataItem\"\x7f\n" +
	"\x12GetUserDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\"\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0e.data.DataTypeR\x04type\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\x99\x01\n" +
	"\x13GetUserDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\n" +
	"data_items\x18\x03 \x03(\v2\x0e.data.DataItemR\tdataItems\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\"\xba\x01\n" +
	"\x11UpdateDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\adata_id\x18\x02 \x01(\tR\x06dataId\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\x12'\n" +
	"\x0fcurrent_version\x18\x06 \x01(\x03R\x0ecurrentVersion\"i\n" +
	"\x12UpdateDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vnew_version\x18\x03 \x01(\x03R\n" +
	"newVersion\"n\n" +
	"\x11DeleteDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\adata_id\x18\x02 \x01(\tR\x06dataId\x12'\n" +
	"\x0fcurrent_version\x18\x03 \x01(\x03R\x0ecurrentVersion\"H\n" +
	"\x12DeleteDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x84\x01\n" +
	"\x0fSyncDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x127\n" +
	"\tlast_sync\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\blastSync\x12\x1f\n" +
	"\vexclude_ids\x18\x03 \x03(\tR\n" +
	"excludeIds\"\xdf\x01\n" +
	"\x10SyncDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\rupdated_items\x18\x03 \x03(\v2\x0e.data.DataItemR\fupdatedItems\x12\x1f\n" +
	"\vdeleted_ids\x18\x04 \x03(\tR\n" +
	"deletedIds\x12A\n" +
	"\x0esync_timestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rsyncTimestamp\"\xd2\x02\n" +
	"\bDataItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\"\n" +
	"\x04type\x18\x03 \x01(\x0e2\x0e.data.DataTypeR\x04type\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\b \x01(\bR\tisDeleted\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"]\n" +
	"\x13CredentialsMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"X\n" +
	"\fTextMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"\x8e\x01\n" +
	"\x0eBinaryMetadata\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"~\n" +
	"\fCardMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tbank_name\x18\x02 \x01(\tR\bbankName\x12\x1b\n" +
	"\tcard_type\x18\x03 \x01(\tR\bcardType\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xb4\x01\n" +
	"\bSyncItem\x12(\n" +
	"\x06action\x18\x01 \x01(\x0e2\x10.data.SyncActionR\x06action\x12+\n" +
	"\tdata_item\x18\x02 \x01(\v2\x0e.data.DataItemR\bdataItem\x12Q\n" +
	"\x13conflict_resolution\x18\x03 \x01(\x0e2 .data.ConflictResolutionStrategyR\x12conflictResolution\"\xd1\x01\n" +
	"\n" +
	"SyncResult\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12(\n" +
	"\x06action\x18\x02 \x01(\x0e2\x10.data.SyncActionR\x06action\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12+\n" +
	"\x11conflict_resolved\x18\x05 \x01(\bR\x10conflictResolved\x12#\n" +
	"\rfinal_version\x18\x06 \x01(\x03R\ffinalVersion\"\xe8\x01\n" +
	"\x16SynchronizeDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12@\n" +
	"\x0elast_sync_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\flastSyncTime\x12$\n" +
	"\x05items\x18\x03 \x03(\v2\x0e.data.SyncItemR\x05items\x12M\n" +
	"\x11conflict_strategy\x18\x04 \x01(\x0e2 .data.ConflictResolutionStrategyR\x10conflictStrategy\"\x9c\x02\n" +
	"\x17SynchronizeDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\aresults\x18\x03 \x03(\v2\x10.data.SyncResultR\aresults\x125\n" +
	"\x0eserver_changes\x18\x04 \x03(\v2\x0e.data.SyncItemR\rserverChanges\x12A\n" +
	"\x0esync_timestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rsyncTimestamp\x12'\n" +
	"\x0ftotal_conflicts\x18\x06 \x01(\x05R\x0etotalConflicts*~\n" +
	"\bDataType\x12\x19\n" +
	"\x15DATA_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DATA_TYPE_CREDENTIALS\x10\x01\x12\x12\n" +
	"\x0eDATA_TYPE_TEXT\x10\x02\x12\x14\n" +
	"\x10DATA_TYPE_BINARY\x10\x03\x12\x12\n" +
	"\x0eDATA_TYPE_CARD\x10\x04*q\n" +
	"\n" +
	"SyncAction\x12\x1b\n" +
	"\x17SYNC_ACTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SYNC_ACTION_CREATE\x10\x01\x12\x16\n" +
	"\x12SYNC_ACTION_UPDATE\x10\x02\x12\x16\n" +
	"\x12SYNC_ACTION_DELETE\x10\x03*\xc6\x01\n" +
	"\x1aConflictResolutionStrategy\x12 \n" +
	"\x1cCONFLICT_RESOLVE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCONFLICT_RESOLVE_BY_VERSION\x10\x01\x12!\n" +
	"\x1dCONFLICT_RESOLVE_BY_TIMESTAMP\x10\x02\x12 \n" +
	"\x1cCONFLICT_RESOLVE_SERVER_WINS\x10\x03\x12 \n" +
	"\x1cCONFLICT_RESOLVE_CLIENT_WINS\x10\x042\xd4\x03\n" +
	"\vDataService\x12<\n" +
	"\tStoreData\x12\x16.data.StoreDataRequest\x1a\x17.data.StoreDataResponse\x126\n" +
	"\aGetData\x12\x14.data.GetDataRequest\x1a\x15.data.GetDataResponse\x12B\n" +
	"\vGetUserData\x12\x18.data.GetUserDataRequest\x1a\x19.data.GetUserDataResponse\x12?\n" +
	"\n" +
	"UpdateData\x12\x17.data.UpdateDataRequest\x1a\x18.data.UpdateDataResponse\x12?\n" +
	"\n" +
	"DeleteData\x12\x17.data.DeleteDataRequest\x1a\x18.data.DeleteDataResponse\x129\n" +
	"\bSyncData\x12\x15.data.SyncDataRequest\x1a\x16.data.SyncDataResponse\x12N\n" +
	"\x0fSynchronizeData\x12\x1c.data.SynchronizeDataRequest\x1a\x1d.data.SynchronizeDataResponseB5Z3github.com/fylgushev/go-diplom-final/pkg/proto/datab\x06proto3"

var (
	file_proto_data_data_proto_rawDescOnce sync.Once
	file_proto_data_data_proto_rawDescData []byte
)

func file_proto_data_data_proto_rawDescGZIP() []byte {
	file_proto_data_data_proto_rawDescOnce.Do(func() {
		file_proto_data_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_data_data_proto_rawDesc), len(file_proto_data_data_proto_rawDesc)))
	})
	return file_proto_data_data_proto_rawDescData
}

var file_proto_data_data_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_data_data_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_data_data_proto_goTypes = []any{
	(DataType)(0),                   // 0: data.DataType
	(SyncAction)(0),                 // 1: data.SyncAction
	(ConflictResolutionStrategy)(0), // 2: data.ConflictResolutionStrategy
	(*StoreDataRequest)(nil),        // 3: data.StoreDataRequest
	(*StoreDataResponse)(nil),       // 4: data.StoreDataResponse
	(*GetDataRequest)(nil),          // 5: data.GetDataRequest
	(*GetDataResponse)(nil),         // 6: data.GetDataResponse
	(*GetUserDataRequest)(nil),      // 7: data.GetUserDataRequest
	(*GetUserDataResponse)(nil),     // 8: data.GetUserDataResponse
	(*UpdateDataRequest)(nil),       // 9: data.UpdateDataRequest
	(*UpdateDataResponse)(nil),      // 10: data.UpdateDataResponse
	(*DeleteDataRequest)(nil),       // 11: data.DeleteDataRequest
	(*DeleteDataResponse)(nil),      // 12: data.DeleteDataResponse
	(*SyncDataRequest)(nil),         // 13: data.SyncDataRequest
	(*SyncDataResponse)(nil),        // 14: data.SyncDataResponse
	(*DataItem)(nil),                // 15: data.DataItem
	(*CredentialsMetadata)(nil),     // 16: data.CredentialsMetadata
	(*TextMetadata)(nil),            // 17: data.TextMetadata
	(*BinaryMetadata)(nil),          // 18: data.BinaryMetadata
	(*CardMetadata)(nil),            // 19: data.CardMetadata
	(*SyncItem)(nil),                // 20: data.SyncItem
	(*SyncResult)(nil),              // 21: data.SyncResult
	(*SynchronizeDataRequest)(nil),  // 22: data.SynchronizeDataRequest
	(*SynchronizeDataResponse)(nil), // 23: data.SynchronizeDataResponse
	(*timestamppb.Timestamp)(nil),   // 24: google.protobuf.Timestamp
}
var file_proto_data_data_proto_depIdxs = []int32{
	0,  // 0: data.StoreDataRequest.type:type_name -> data.DataType
	15, // 1: data.GetDataResponse.data_item:type_name -> data.DataItem
	0,  // 2: data.GetUserDataRequest.type:type_name -> data.DataType
	15, // 3: data.GetUserDataResponse.data_items:type_name -> data.DataItem
	24, // 4: data.SyncDataRequest.last_sync:type_name -> google.protobuf.Timestamp
	15, // 5: data.SyncDataResponse.updated_items:type_name -> data.DataItem
	24, // 6: data.SyncDataResponse.sync_timestamp:type_name -> google.protobuf.Timestamp
	0,  // 7: data.DataItem.type:type_name -> data.DataType
	24, // 8: data.DataItem.created_at:type_name -> google.protobuf.Timestamp
	24, // 9: data.DataItem.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 10: data.SyncItem.action:type_name -> data.SyncAction
	15, // 11: data.SyncItem.data_item:type_name -> data.DataItem
	2,  // 12: data.SyncItem.conflict_resolution:type_name -> data.ConflictResolutionStrategy
	1,  // 13: data.SyncResult.action:type_name -> data.SyncAction
	24, // 14: data.SynchronizeDataRequest.last_sync_time:type_name -> google.protobuf.Timestamp
	20, // 15: data.SynchronizeDataRequest.items:type_name -> data.SyncItem
	2,  // 16: data.SynchronizeDataRequest.conflict_strategy:type_name -> data.ConflictResolutionStrategy
	21, // 17: data.SynchronizeDataResponse.results:type_name -> data.SyncResult
	20, // 18: data.SynchronizeDataResponse.server_changes:type_name -> data.SyncItem
	24, // 19: data.SynchronizeDataResponse.sync_timestamp:type_name -> google.protobuf.Timestamp
	3,  // 20: data.DataService.StoreData:input_type -> data.StoreDataRequest
	5,  // 21: data.DataService.GetData:input_type -> data.GetDataRequest
	7,  // 22: data.DataService.GetUserData:input_type -> data.GetUserDataRequest
	9,  // 23: data.DataService.UpdateData:input_type -> data.UpdateDataRequest
	11, // 24: data.DataService.DeleteData:input_type -> data.DeleteDataRequest
	13, // 25: data.DataService.SyncData:input_type -> data.SyncDataRequest
	22, // 26: data.DataService.SynchronizeData:input_type -> data.SynchronizeDataRequest
	4,  // 27: data.DataService.StoreData:output_type -> data.StoreDataResponse
	6,  // 28: data.DataService.GetData:output_type -> data.GetDataResponse
	8,  // 29: data.DataService.GetUserData:output_type -> data.GetUserDataResponse
	10, // 30: data.DataService.UpdateData:output_type -> data.UpdateDataResponse
	12, // 31: data.DataService.DeleteData:output_type -> data.DeleteDataResponse
	14, // 32: data.DataService.SyncData:output_type -> data.SyncDataResponse
	23, // 33: data.DataService.SynchronizeData:output_type -> data.SynchronizeDataResponse
	27, // [27:34] is the sub-list for method output_type
	20, // [20:27] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_data_data_proto_init() }
func file_proto_data_data_proto_init() {
	if File_proto_data_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_data_data_proto_rawDesc), len(file_proto_data_data_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_data_data_proto_goTypes,
		DependencyIndexes: file_proto_data_data_proto_depIdxs,
		EnumInfos:         file_proto_data_data_proto_enumTypes,
		MessageInfos:      file_proto_data_data_proto_msgTypes,
	}.Build()
	File_proto_data_data_proto = out.File
	file_proto_data_data_proto_goTypes = nil
	file_proto_data_data_proto_depIdxs = nil
}
